myfirstdjango/myfirstdjango/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myfirstdjango.views.home', name='home'),
    # url(r'^myfirstdjango/', include('myfirstdjango.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    url(r'^myfirstapp/$', 'myfirstapp.views.index'),
    url(r'^myfirstapp/info/$', 'myfirstapp.views.info'),
    url(r'^myfirstapp/(?P<poll_id>\d+)/$', 'myfirstapp.views.detail'),
    url(r'^myfirstapp/(?P<poll_id>\d+)/results/$', 'myfirstapp.views.results'),
    url(r'^myfirstapp/(?P<poll_id>\d+)/vote/$', 'myfirstapp.views.vote'),    
    
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': '/home/virtualmininetu/djcode/python-test/myfirstdjango/media'}),
    url(r'^admin/', include(admin.site.urls) ),
    url(r'^SdnBoss/$', 'myfirstapp.SwHo.switchesInfo'),    #WORKINPROGRESS (new)
    url(r'^GoSwitch/(?P<DpidUrl>.+)/$', 'myfirstapp.SingleSwitch.singleSwitch'),    #WORKINPROGRESS HERE
    url(r'^Boss/FloodlightContrLoadedModules/$', 'myfirstapp.LoadMod.LoadedMod'),
    url(r'^prova/$', 'myfirstapp.prova1.prova'),    #DEVELOPMENT: to parse new scripting
    url(r'^casa/$', 'myfirstapp.debug1.debug1'),    #DEVELOPMENT: to parse new scripting
    url(r'^bug1/$', 'myfirstapp.bug1.bugOne'),    #DEVELOPMENT: to parse session 
    url(r'^bug2/$', 'myfirstapp.bug2.bugTwo'),    #DEVELOPMENT: to parse session 
    url(r'^bug3/$', 'myfirstapp.bug3.bugThree'),    #DEVELOPMENT: to parse session 
    url(r'^bug4/$', 'myfirstapp.bug4.bugFour'),    #DEVELOPMENT: to parse session 
    url(r'^login/$', 'myfirstapp.LoginView.loginTry'),    #login view url
    #url(r'^login/$', 'django.contrib.auth.views.login', {'LoginTemp.html': 'LoginTemp.html'}),    #to login
    url(r'^logout/$', 'myfirstapp.LoginView.logoutView'),
    url(r'^usereg/$', 'myfirstapp.LoginView.regView'),
    url(r'^action/(?P<username>.*)', 'myfirstapp.LoginView.authUserInfo'),
)

myfirstdjango/myfirstapp/models.py
from django.db import models

# Create your models here.
class Poll(models.Model):
    def __unicode__(self):
        return self.question    
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Choice(models.Model):
    def __unicode__(self):
        return self.choice
    poll = models.ForeignKey(Poll)
    choice = models.CharField(max_length=200)
    votes = models.IntegerField()


#test for form

#table with user
#class UserSubmit (models.Model):
    #username = models.CharField(max_length = 60)
    #password = models.CharField(max_length = 60)
    #mailAdd = models.CharField(max_length = 120)

myfirstdjango/myfirstapp/forms.py
# to define form for login
# I use newforms

#from django.utils.translation import ugettext_lazy as _, ugettext
#from django import forms    #form module
#from django.contrib.auth import login, authenticate    #maybe it isn't need here???
##from django.contrib.auth import User    #maybe no
#from django.contrib.auth.models import User
#import string
#from django.forms import ModelForm    #to use class meta to create a form

from django import forms    #it loads form module
#from django.contrib.auth.models import User
from django.forms import ModelForm    #to use class meta to create a form
from django.contrib.auth.models import User    #for the registration form



# form from user instance
#class LoginForm (forms.ModelForm):
    #class Meta:
        #model = User
        #fields = ('username', 'password' )



#the login form

class LoginForm (forms.Form):    #to define the login form
    username = forms.CharField( label=('username'), widget = forms.TextInput(attrs={'placeholder' : 'username'}),
                                error_messages={'required' : 'you didn\'t insert your username'} )
    password = forms.CharField( label=('password'), widget=forms.PasswordInput(attrs={'placeholder' : 'your password'}),
                                error_messages={'required' : 'insert your password please'} )
    def clean_password(self):    #check if the password is longer than 5 words
        passwordCheck = self.cleaned_data.get('password')
        if len (passwordCheck) < 7:
            raise forms.ValidationError('not long enough')
        return passwordCheck
    def __unicode__(self):
        return self.username



#the registration form

class RegForm (forms.Form):
    firstName = forms.CharField( label=('First Name'), required=True, 
                                widget = forms.TextInput(attrs={'placeholder' : 'First Name'}),
                                error_messages={'required' : 'insert your first name please'} )
    lastName = forms.CharField( label=('Last Name'), required=True,
                                widget = forms.TextInput(attrs={'placeholder' : 'Last Name'}),
                                error_messages={'required' : 'insert your last name please'} )
    username = forms.CharField( label=('Username'), max_length=77, required=True,
                                widget = forms.TextInput(attrs={'placeholder' : 'username'}),
                                error_messages={'required' : ' insert your username please'},
                                help_text="max 30 characters" )
    email = forms.EmailField( label=('email'), widget = forms.TextInput(attrs={'placeholder' : 'email'} ),
                                required=True, error_messages={'required' : 'insert your email address please'} )
    pass_One = forms.CharField( label=('Password'), widget=forms.PasswordInput(attrs={'placeholder' : 'password'}) ,
                            error_messages={'required' : 'insert the password, please'} )
    pass_Two = forms.CharField( label=('Repeat Password'), widget=forms.PasswordInput(attrs={'placeholder' : 'confirm password'}),
                                error_messages={'required' : 'confirm the password please'} )
    def clean_username(self):    #unique username check
        usernameChk = self.cleaned_data.get('username')
        try:
            User.objects.get(username=usernameChk)
            raise forms.ValidationError("This username already exists")
        except User.DoesNotExist:
            return usernameChk
    def clean_email(self):    #unique email address check
        emailChk = self.cleaned_data.get('email')
        try:
            User.objects.get(email=emailChk)
            raise forms.ValidationError("This email address already exists")
        except User.DoesNotExist:
            return emailChk
    def clean_pass_One(self):    #password minimun seven control
        passOne = self.cleaned_data.get("pass_One")
        if len( passOne ) < 7:
            raise forms.ValidationError("7 min")
        return passOne
    def clean_pass_Two(self):    #password 7 min and matching passwords check
        passTwo = self.cleaned_data.get("pass_Two")
        passOne = self.cleaned_data.get("pass_One")
        if len( passTwo ) < 7:
            raise forms.ValidationError("7 min")
        else:
            if passOne != passTwo:
                raise forms.ValidationError("the password didn't match")
        return passTwo

#authenticated user action form


OPTION= ( 
        ("op1", "profilo"),
        ("opt2", "logOut")
        )

class authUser(forms.Form):

    c = "casa"
    #UserAction = forms.CharField(label=c, widget=forms.Select(choices = [ (1,2) ] ) )
    UserAction = forms.ChoiceField( label=c, choices = OPTION)

myfirstdjango/myfirstapp/views.py
from django.shortcuts import render
from myfirstapp.models import Poll
import requests
import json



def index(request):
    latest_poll_list = Poll.objects.all().order_by('-pub_date')[:5]
#    t = loader.get_template('myfirstapp/index.html')
#    c = Context({
#        'latest_poll_list': latest_poll_list,
#    })
    context = { 'latest_poll_list': latest_poll_list, }
#    return HttpResponse(t.render(c))
    return render (request, 'myfirstapp/index.html', context)
#    return HttpResponse("Hello, world. You're at the poll index.")

def info(request):
    #latest_poll_list = Poll.objects.all().order_by('-pub_date')[:5]

    r = requests.get('http://localhost:8080/wm/core/controller/switches/json')
    #json_data = r.json()

    a = []
    a.append( json.dumps(r.json(), sort_keys = False, indent = 4))

    context = { 'pluto': a, }
    return render (request, 'myfirstapp/index.html', context)


def detail(request, poll_id):
    return HttpResponse("You're looking at poll %s." % poll_id)

def results(request, poll_id):
    return HttpResponse("You're looking at the results of poll %s." % poll_id)

def vote(request, poll_id):
    return HttpResponse("You're voting on poll %s." % poll_id)

myfirstdjango/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

  <head>
    <title> BOSS - Boss is Open Source Sdn</title>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
<!--
    <link type="text/css" href="/media/common/css/trac.css" rel="stylesheet"> 
-->
    <link type="text/css" href="/media/common/css/wiki.css" rel="stylesheet">
    <link href="/media/site/style.css" type="text/css" rel="stylesheet">
  </head>
  <body>
    <div id="boss-home">
      <div id="django-container">
        <div id="django-header">
          <h1 id="django-logo"><a href="https://github.com/boss-sdn"><img src="/media/img/site/boss_logo.gif" alt="boss" /></a></h1>
          
        <ul id="django-nav-global">
        <li id="django-active-nav"><a href="/SdnBoss/">Home</a></li>
        <li><a href="https://github.com/boss-sdn">Documentation</a></li>
        <li> {% if user.is_authenticated %}
                 <a href=/action/{{ user.username }}> {{ user.username }} </a>
             {% else %}
                 <a href="/login"> Login </a>
             {% endif %}</li>
                </ul>
        </div>
        <div id="django-billboard">
          <h2><a href="/">Boss index</a></h2>
        </div>
        <div id="django-columnwrap">
          <div id="django-content-main">
          <p> 
            {% block title %} {% endblock title %}
            {% block content %} {% endblock content %}
            {% block SwHo %} {% endblock SwHo %}
            {% block SingleSwitch %} {% endblock SingleSwitch %}
            {% block LoadMod %} {% endblock LoadMod %}
            {% block prova %} {% endblock prova %}
            {% block debug1%} {% endblock debug1%}
            {% block bug1 %} {% endblock bug1 %}
            {% block bug2 %} {% endblock bug2 %}
            {% block bug3 %} {% endblock bug3 %}
            {% block bug4 %} {% endblock bug4 %}
            {% block LoginTemp %} {% endblock LoginTemp %}
          </p>
          </div>
        </div>
        <div id="django-footer">
          <p>© 2013 <a href="https://github.com/boss-sdn">Boss is Open Source SDN</a> 
          
          </p>
        </div>
      </div>
    </div>
  </body>
</html> 

myfirstdjango/templates/myfirstapp/LoadMod.html
{% extends "./index.html" %}

{% block LoadMod %}

<div> 
    <p>
        <h1> <b> ({{ nMod }}) loaded modules </b> </h2>
        <br></br>
        {% for val in lMod %}
            {{ val|linebreaks }}
        {% endfor %}
    </p>
    <br> </br>
    <p>
        <h3>n.f=net.floodlightcontroller</h3>
    </p>
</div>

{% endblock LoadMod %}

myfirstdjango/templates/myfirstapp/LoginTemp.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

{% extends "./index.html" %}

{% block content %}

<!--
template for login page that use a form
-->





<!-- IT WORKS-->


<div>
    <form action="/login/" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
        {{message}}
    </form> 
</div>

<!--
<body>
    <div>
        <form action="/login/" method="post">{% csrf_token %}
            {{ form.non_field_errors }}
            <div>
                {{ form.username.errors }}
                <label for="username">Username</label>
                <input type="text" id="id_username" name="username"  placeholder="username">
            </div>
            <div>
                {{ form.password.errors }}
                <label for="password"> Password </label>
                <input type="password" name="password" id="id_password" placeholder="Password">
            </div> 
            <input type="submit" value="Submit" />
            {{ message }}
        </form> 
    </div>
</body>
-->



<!--
<div id="stylized" class="myform">
-->


<!--
<div> 
    <body>
        <form id="id_LoginForm" action="/login/" method = "post"> {% csrf_token %}
            {{message}}
            <div>
                <label for="username">Username</label>
            </div>
            <div>
            <input type="text" id="id_username" name="username"  placeholder="Username">
            </div>
            <div>
                <label for="id_password">Password</label>
            </div>
            <div>
                <input type="password" name="password" id="password" placeholder="Password">
            </div>
            <p> <input type="submit" value="SignIn" /> </p>
        </form>
    </body>
</div>



-->


<!--
<div>
    <form action="/login/" method="post"> {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
            {{ form.subject.errors }}
            <label for="id_subject">Username:</label>
            {{ form.username }}
        </div>
        <div class="fieldWrapper">
            {{ form.message.errors }}
            <label for="id_message">Password:</label>
            {{ form.password }}
        </div>
        <p> <input type="submit" value="SignIn" /> </p>
    </form>
</div
-->




<!--
the last attempt, for my css
-->


<!--
<head>
    <link rel="stylesheet" type="text/css" href="/media/site/style.css" />
</head>
<body>
    <div id="django-formcss">
<!--
        <form method="post">
-->
<!--
        <fieldset>
            <legend>A compact inline form</legend>
            <input type="email" placeholder="Email">
            <input type="password" placeholder="Password">
            <label for="remember">
            <input id="remember" type="checkbox"> Remember me
            </label>
            <button type="submit" class="pure-button pure-button-primary">Sign in</button>
        </fieldset>
<!--
        </form>
-->
<!--
    </div>
</body>
-->

{% endblock content %}

myfirstdjango/templates/myfirstapp/RegTemp.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

{% extends "./index.html" %}

{% block content %}


<!--
<body>
    <div>
        <form action="/usereg/" method="post">{% csrf_token %}
            {{ form.non_field_errors }}
            <div> 
                <label for=firstName>First Name</label>
                <input type="text" id="id_firstName" name="FirstName" placeholder="First Name"> 
                {{form.firstName.errors}}
            </div>
            <div>
                <label for=lastName>Last Name</label>
                <input type="text" id="id_lastName" name="LastName" placeholder="Last Name"> 
                {{form.lastName.errors}}
            </div>
            <div>
                <label for="username">Username</label>
                <input type="text" id="id_username" name="username" placeholder="username">
                {{ form.username.errors }}
            </div>
            <div>
                <label for="email">Email</label>
                <input type="text" id="id_email" name="email" placeholder="email">
                {{ form.email.errors }}
            </div>
            <div>
                <label for="pass_One"> Password </label>
                <input type="password" name="passwordOne" id="id_passwordOne" placeholder="Password">
                {{ form.pass_One.errors }}
            </div> 
            <div>
                {{ form.pass_Two.errors }}
                <label for="pass_Two"> Confirm Password </label>
-->
<!--
                <input type="password" name="passwordTwo" id="id_passwordTwo" placeholder="Password">
-->
<!--
                {{form.pass_Two}}
            </div> 
            <input type="submit" value="Sign Up for Boss" />
            {{ message }}
        </form> 
    </div>
</body>
-->




<div>
    <form action="/usereg/" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
        {{message}}
    </form> 
</div>


{% endblock content %}

myfirstdjango/templates/myfirstapp/SingleSwitch.html
{% extends "./index.html" %}
{% block SingleSwitch %}

<div> <!-- it shows single switches info -->
    <caption>
        <table border="4" cellpadding="7">
        <h1>SWITCH {{dUrl}}</h1>
    </caption>
    <thead>
        <tr>
            <th><b>Port Number</b></th>
            <th><b>Name Port</b></th>
            <th><b>State</b></th>
            <th><b>MAC Address</b></th>
            <th><b>Tx Bytes</b></th>
            <th><b>Rx Bytes</b></th>
            <th><b>Tx Packets</b></th>
            <th><b>Rx Packets</b></th>
            <th><b>Tx Dropped</b></th>
            <th><b>Rx Dropped</b></th>
            <th><b>Collisions</b></th>
            <th><b>Rx Frame Errors</b></th>
        </tr>
    </thead>
    <body>
        <tr>
            <td align="center">
                {% for val in nsSwPort %} <span style="color:{% cycle 'blue' 'black' %}">
                    {{ val|linebreaks }} 
                </span> {% endfor %}
            </td>
            <td align="center">
                {% for val in SwInfo %} <span style="color:{% cycle 'blue' 'black' %}">
                    {{ val.pName|linebreaks }}
                </span> {% endfor %}</td>
            <td align="center"> 
                {% for val in SwInfo %} <span style="color:{% cycle 'blue' 'black' %}">
                    {{val.pState|linebreaks}}
                </span> {% endfor %}
            </td>
            <td align="center">
                {% for val in SwInfo %} <span style="color:{% cycle 'blue' 'black' %}">
                    {{ val.pMac|linebreaks }}
                </span> {% endfor %}
            </td>
            <td align="center">
                {% for val in SwInfo %} <span style="color:{% cycle 'blue' 'black' %}">
                    {{ val.pTxB|linebreaks }}
                </span> {% endfor %}
            </td>
            <td align="center">
                {% for val in SwInfo %} <span style="color:{% cycle 'blue' 'black' %}">
                    {{ val.pRxB|linebreaks }}
                </span> {% endfor %}
            </td>
            <td align="center">
                {% for val in SwInfo %} <span style="color:{% cycle 'blue' 'black' %}">
                    {{ val.pTxP|linebreaks }}
                </span> {% endfor %}
            </td>
            <td align="center">
                {% for val in SwInfo %} <span style="color:{% cycle 'blue' 'black' %}">
                    {{ val.pRxP|linebreaks }}
                </span> {% endfor %}
            </td>
            <td align="center">
                {% for val in SwInfo %} <span style="color:{% cycle 'blue' 'black' %}">
                    {{ val.pTxDrop|linebreaks }}
                </span> {% endfor %}
            </td>
            <td align="center">
                {% for val in SwInfo %} <span style="color:{% cycle 'blue' 'black' %}">
                    {{ val.pRxDrop|linebreaks }}
                </span> {% endfor %}
            </td>
            <td align="center">
                {% for val in SwInfo %} <span style="color:{% cycle 'blue' 'black' %}">
                    {{ val.pColl|linebreaks }}
                </span> {% endfor %}
            </td>
            <td align="center">
                {% for val in SwInfo %} <span style="color:{% cycle 'blue' 'black' %}">
                    {{ val.pRxFrEr|linebreaks }}
                </span> {% endfor %}
            </td>
        </tr>
    </body>
        </table>
</div>
<div> <!-- it shows flows info-->
    <caption>
        <table border="4" cellpadding="7">
        <h1>Flow {{nFlow}}</h1>
    </caption>
    <thead>
        <tr>
            <th rowspan="2"><b>Cookie</b></th>
            <th rowspan="2"><b>Priority</b></th>
            <th colspan="5"><b>Match</b></th>
            <th colspan="2"><b>Action</b></th>
            <th rowspan="2"><b>Packets</b></th>
            <th rowspan="2"><b>Bytes</b></th>
            <th rowspan="2"><b>Age</b></th>
            <th rowspan="2"><b>TimeOut</b></th>
        </tr>
        <tr>
            <th>Port</th>
            <th>VLAN</th>
            <th>Prio</th>
            <th>Source</th>
            <th>Destination</th>
            <th>Type</th>
            <th>Port</th>
    </thead>
    <body>
        <td align="center" style="color:blue"> 
            {% for val in flowInfo %}
                {{ val.fCkie|linebreaks }}
            {% endfor %}
        </td>
        <td align="center" style="color:blue">
            {% for val in flowInfo %}
                {{ val.fPrio|linebreaks }}
            {% endfor %}
        </td>
        <td align="center" style="color:blue">
            {% for val in flowInfo %}
                {{ val.fM_port|linebreaks }}
            {% endfor %}
        </td>
        <td align="center" style="color:blue">
            {% for val in flowInfo %}
                {{ val.fM_vlan|linebreaks }}
            {% endfor %}
        </td>
        <td align="center" style="color:blue">
            {% for val in flowInfo %}
                {{ val.fM_prio|linebreaks }}
            {% endfor %}
        </td>
        <td align="center" style="color:blue">
            {% for val in flowInfo %}
                {{ val.fM_src|linebreaks }}
            {% endfor %}
        </td>
        <td align="center" style="color:blue">
            {% for val in flowInfo %}
                {{ val.fM_dst|linebreaks }}
            {% endfor %}
        </td>
        <td align="center" style="color:blue">
            {% for val in flowInfo %}
                {% for x in val.fA_type %}
                    {{ x|linebreaks }}
                {% endfor %}
            {% endfor %}
        </td>
        <td align="center" style="color:blue">
            {% for val in flowInfo %}
                {% for x in val.fA_port %}
                    {{ x|linebreaks }}
                {% endfor %}
            {% endfor %}
        </td>
        <td align="center" style="color:blue">
            {% for val in flowInfo %}
                {{ val.fPk|linebreaks }}
            {% endfor %}
        </td>
        <td align="center" style="color:blue">
            {% for val in flowInfo %}
                {{ val.fB|linebreaks }}
            {% endfor %}
        </td>
        <td align="center" style="color:blue">
            {% for val in flowInfo %}
                {{ val.fAge|linebreaks }}
            {% endfor %}
        </td>
        <td align="center" style="color:blue">
            {% for val in flowInfo %}
                {{ val.fTO|linebreaks }}
            {% endfor %}
        </td>
    </body>
        </table>
</div>
<!--
below for debug
-->
<!--
<div> 
    <h1> debug </h1>
    <h2> session id {{bug1SS}} </h2>
    <h2> {{bugSS}} </h2> 
    <a href=/casa> {{dUrl}} </a>
    
</div>

-->







{% endblock SingleSwitch %}

myfirstdjango/templates/myfirstapp/SingleSwitch_v0.html
{% extends "./index.html" %}
{% block SingleSwitch %}






    <div>
    <pre>
    <table border="4" cellpadding="7">
    <h1>SWITCH {{dUrl}}</h1>
    <tr>
    <th>Port Number</th><th>Name Port</th><th>State</th><th>MAC Address</th><th>Tx Bytes</th><th>Rx Bytes</th><th>Tx Packets</th>
<th>Rx Packets</th><th>Tx Dropped</th><th>Rx Dropped</th><th>Collisions</th><th>Rx Frame Errors</th>
    </tr>
    <tr>
    <td align="center">{% for val in nsSwPort %}
<a style="color:{% cycle 'blue' 'black' %}"> {{ val }} </a>
        {% endfor %}</td>    <td align="center">{% for val in SwInfo %}
<a style="color:{% cycle 'blue' 'black' %}"> {{ val.pName }} </a>
        {% endfor %}</td>    <td align="center">{% for val in SwInfo %}
<a style="color:{% cycle 'blue' 'black' %}"> {{ val.pState }} </a>
        {% endfor %}</td>    <td align="center">{% for val in SwInfo %}
<a style="color:{% cycle 'blue' 'black' %}"> {{ val.pMac }} </a>
        {% endfor %}</td>    <td align="center">{% for val in SwInfo %}
<a style="color:{% cycle 'blue' 'black' %}"> {{ val.pTxB }} </a>
        {% endfor %}</td>    <td align="center">{% for val in SwInfo %}
<a style="color:{% cycle 'blue' 'black' %}"> {{ val.pRxB }} </a>
        {% endfor %}</td>    <td align="center">{% for val in SwInfo %}
<a style="color:{% cycle 'blue' 'black' %}"> {{ val.pTxP }} </a>
        {% endfor %}</td>    <td align="center">{% for val in SwInfo %}
<a style="color:{% cycle 'blue' 'black' %}"> {{ val.pRxP }} </a>
        {% endfor %}</td>    <td align="center">{% for val in SwInfo %}
<a style="color:{% cycle 'blue' 'black' %}"> {{ val.pTxDrop }} </a>
        {% endfor %}</td>    <td align="center">{% for val in SwInfo %}
<a style="color:{% cycle 'blue' 'black' %}"> {{ val.pRxDrop }} </a>
        {% endfor %}</td>    <td align="center">{% for val in SwInfo %}
<a style="color:{% cycle 'blue' 'black' %}"> {{ val.pColl }} </a>
        {% endfor %}</td>    <td align="center">{% for val in SwInfo %}
<a style="color:{% cycle 'blue' 'black' %}"> {{ val.pRxFrEr }} </a>    
        {% endfor %}</td>
    </tr>
    </table>
    </pre>
    </div>


{% endblock SingleSwitch %}

myfirstdjango/templates/myfirstapp/authUser.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">


{% extends "./index.html" %}

{% block content %}

<head>
    <div>
        <h1> {{ user.username }} profile </h1>
    </div>
</head>
<body>
    <div>
        Full name: {{ name }}
    </div>
</body>

{% endblock content %}

myfirstdjango/templates/myfirstapp/bug1.html
{% extends "./index.html" %}
{% block bug1 %}

<div>
    <h1> session try </h1>
    <h2> output </h2> {{bug1Out}}
    <h2> session id </h2> {{bug1Id}}
    <h2> time stamp </h2> {{bug1TS}}
</div>



{% endblock bug1 %}

myfirstdjango/templates/myfirstapp/debug1.html
<!--
for debug
-->

{% extends "./index.html" %}
{% block debug1 %}
<div> 
    <h1> TRY </h1> 
    <h2> session id {{bug1D}} </h2>
    <h2> {{bugD}} </h2>
</div>
    <a href="/GoSwitch/44%3A44%3A44%3A44%3A44%3A44%3A44%3A44/"> Back 44 </a>





{% endblock debug1 %}

myfirstdjango/templates/myfirstapp/loadedModulesCopy.html
{% extends "./index.html" %}

{% block loadedModules %}

<div>
<pre> <a {{ lMod }} </a> </pre>
</div>

{% endblock loadedModules %}